CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT CHECK(role IN ('admin', 'employee')) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
